### ISSUE TITLE
ERROR TypeError: vega_embed__WEBPACK_IMPORTED_MODULE_1__ is not a function

### ISSUE THREAD

**Issue by vbalaned** [shusson/vega-lite-demo#1]
Hi,

  I have my local copy of this repo and trying run as per instructions. I am getting the following error

ERROR TypeError: vega_embed__WEBPACK_IMPORTED_MODULE_1__ is not a function
    at AppComponent.push../src/app/app.component.ts.AppComponent.ngOnInit (app.component.ts:29)
    at checkAndUpdateDirectiveInline (core.js:9243)
    at checkAndUpdateNodeInline (core.js:10507)
    at checkAndUpdateNode (core.js:10469)
    at debugCheckAndUpdateNode (core.js:11102)
    at debugCheckDirectivesFn (core.js:11062)
    at Object.eval [as updateDirectives] (AppComponent_Host.ngfactory.js? [sm]:1)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:11054)
    at checkAndUpdateView (core.js:10451)

i am not sure, is there any package incompatiblity or something similar? please help

**Comment by shusson** [comment]
what version of angular cli are you using?

**Comment by vbalaned** [comment]
Angular CLI: 6.2.
Node: 8.12.0
Angular: 6.1.9

**Comment by shusson** [comment]
You'll need to install `angular-cli` with the version specified in https://github.com/shusson/vega-lite-demo/blob/master/package.json#L32.

**Comment by vbalaned** [comment]
Thanks for quick responses. I have a doubt, i have installed angular cli latest version (6.2)globally sometime ago. Now I have a separate folder for this vegalite demo app and installed all modules locally, which has recommended cli version ("@angular/cli": "1.2.2").  In this case it should refer to the locally available ng cli than gloabally installed one.  Please correct me if i am wrong.

**Comment by vbalaned** [comment]
I have observed the following error in ng serve console:

ERROR in src/app/app.component.ts(30,5): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("C:/Vega/vegademo/node_modules/vega-embed/build/src/embed")' has no compatible call signatures.

**Comment by vbalaned** [comment]
Hi, I think i have got it. The way of importing vega-embed makes difference. 
https://github.com/shusson/vega-lite-demo/blob/6446e8210968bb3456b35bbccc3bf1fd2409db7e/src/app/app.component.ts#L2

If i chagne it to   " import embed from 'vega-embed';  "
It has started working

Thanks for your help.

**Comment by shusson** [comment]
👍 good to hear
